

USE WAREHOUSE ingest_wh;
USE DATABASE sales_analytics;



CREATE OR REPLACE USER yukta
PASSWORD='*******'
DEFAULT_ROLE=data_engineer
DEFAULT_WAREHOUSE=ingest_wh
MUST_CHANGE_PASSWORD=TRUE;

CREATE OR REPLACE USER vaishnavi
PASSWORD='******'
DEFAULT_ROLE=data_engineer
DEFAULT_WAREHOUSE=ingest_wh
MUST_CHANGE_PASSWORD=TRUE;

CREATE OR REPLACE USER nishita
PASSWORD='*******'
DEFAULT_ROLE=data_engineer
DEFAULT_WAREHOUSE=ingest_wh
MUST_CHANGE_PASSWORD=TRUE;



ALTER USER yukta SET MUST_CHANGE_PASSWORD = FALSE;
ALTER USER nishita SET MUST_CHANGE_PASSWORD = FALSE;
ALTER USER vaishnavi SET MUST_CHANGE_PASSWORD = FALSE;


GRANT ROLE data_engineer TO USER yukta;
GRANT ROLE data_engineer TO USER vaishnavi;
GRANT ROLE data_engineer TO USER nishita;



GRANT ROLE data_engineer TO ROLE SYSADMIN;

