CREATE OR REPLACE USER yukta
PASSWORD='Password@123'
DEFAULT_ROLE=data_engineer
DEFAULT_WAREHOUSE=ingest_wh
MUST_CHANGE_PASSWORD=TRUE;

CREATE OR REPLACE USER vaishnavi
PASSWORD='Password@123'
DEFAULT_ROLE=data_engineer
DEFAULT_WAREHOUSE=ingest_wh
MUST_CHANGE_PASSWORD=TRUE;

CREATE OR REPLACE USER nishita
PASSWORD='Password@123'
DEFAULT_ROLE=data_engineer
DEFAULT_WAREHOUSE=ingest_wh
MUST_CHANGE_PASSWORD=TRUE;